apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  generation: 1
  labels:
    app: react-redux
  name: react-redux
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-redux
  template:
    metadata:
      labels:
        app: react-redux
    spec:
      containers:
      - image: docker.io/homeroahm/react-redux:v1
        imagePullPolicy: IfNotPresent
        name: react-redux
        resources: {}
      restartPolicy: Always

