name: K8s cluster

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Kubectl - Google Cloud GKE cluster
        uses: ameydev/gke-kubectl-action@master
        env:
          PROJECT_ID: ${{ secrets.GKE_PROJECT }}
          APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
          CLUSTER_NAME: ${{ secrets.CLUSTER_NAME }}
          ZONE_NAME: ${{ secrets.ZONE_NAME }}
        with: 
          args: get all
        