name: K8s cluster

on:
  workflow_dispatch:

jobs:
  create-vm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Kubectl - Google Cloud GKE cluster
        uses: ameydev/gke-kubectl-action@master
        env:
          PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
          APPLICATION_CREDENTIALS: ${{ secrets.GCP_GOOGLE_CREDENTIALS }}
          CLUSTER_NAME: ${{ secrets.CLUSTER_NAME }}
          ZONE_NAME: ${{ secrets.ZONE_NAME }}

      - with: 
          args: get all
        